#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# echo "HOOK -> pre-commit: Validate branch name"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
PREFIX_BRANCH="feature|fix|hotfix|alpha|staging|uat|release"
REGEX_BRANCH="^($PREFIX_BRANCH)"

if ! [[ $BRANCH =~ $REGEX_BRANCH ]]; then
    echo "Please rename your branch with '($PREFIX_BRANCH)/<module name>' syntax"
    exit 1;
fi
