#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "WARNING: pre-commit hook, validate branch and commit message"
BRANCH=$(git rev-parse --abbrev-ref HEAD)
PREFIX_BRANCH="feature|fix|hotfix|alpha|staging|release"
REGEX="^($PREFIX_BRANCH)*"

if ! [[ $BRANCH =~ $REGEX ]]; then
    echo "Please rename your branch with '($PREFIX_BRANCH)/<msg>' syntax"
    exit 1;
fi
