#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "WARNING: prepare-commit-msg hook, validate msg"
COMMIT_MSG=$(cat "$1")
COMMIT_SOURCE=$2
branchName=$(git rev-parse --abbrev-ref HEAD)
if $branchName > "^[feature|fix|hotfix]\/\w+$" 2>&1
then
    echo $branchName
fi
echo $COMMIT_MSG
